export enum Parameters {
  BACKGROUND_COLOR = "#031228ff",
  MAIN_COLOR = "#faf20fff",

  PLAYER_SPEED = 10,
  PLAYER_HEALTH = 10,

  BULLET_SPEED = 5,
  BULLET_RADIUS = 8,
  BULLET_MAX = 100,
  BULLET_COOLDOWN = 300,
  BULLET_COLOR = "#a8cbffff",

  ENEMY_POINTS = 100,
  ENEMY_SPEED = 5,
  ENEMY_MARGIN = 30,
  ENEMIES_LAPS = 20,
  ENEMIES_MIN_COUNT = 17,
}
